/* GEMINII Tailwind v3 preset. Generated by tools/build_package.py. Do not edit by hand.
 * Usage: module.exports = { presets: [require('./tokens/tailwind.preset.cjs')], content: [...] }
 * Replaces Tailwind's default palette with the three brand colors. Import css/brand.css for themes and components. */
module.exports = {
  theme: {
    "colors": {
      "transparent": "transparent",
      "current": "currentColor",
      "black": "#000000",
      "teal": "#00c7c5",
      "white": "#ffffff",
      "bg": "var(--gm-bg)",
      "fg": "var(--gm-fg)"
    },
    "fontFamily": {
      "sans": [
        "Arvo",
        "Rockwell",
        "Roboto Slab",
        "Georgia",
        "serif"
      ],
      "arvo": [
        "Arvo",
        "Rockwell",
        "Roboto Slab",
        "Georgia",
        "serif"
      ]
    },
    "fontWeight": {
      "regular": "400",
      "bold": "700"
    },
    "fontSize": {
      "display": [
        "clamp(3rem, calc(1.23913rem + 7.8261vw), 7.5rem)",
        {
          "lineHeight": "1.0",
          "fontWeight": "700"
        }
      ],
      "h1": [
        "clamp(2.25rem, calc(1.36957rem + 3.9130vw), 4.5rem)",
        {
          "lineHeight": "1.1111",
          "fontWeight": "700"
        }
      ],
      "h2": [
        "clamp(1.75rem, calc(1.26087rem + 2.1739vw), 3rem)",
        {
          "lineHeight": "1.1667",
          "fontWeight": "700"
        }
      ],
      "h3": [
        "clamp(1.5rem, calc(1.30435rem + 0.8696vw), 2rem)",
        {
          "lineHeight": "1.25",
          "fontWeight": "700"
        }
      ],
      "body-lg": [
        "clamp(1.25rem, calc(1.15217rem + 0.4348vw), 1.5rem)",
        {
          "lineHeight": "1.5",
          "fontWeight": "400"
        }
      ],
      "body": [
        "1.125rem",
        {
          "lineHeight": "1.5556",
          "fontWeight": "400"
        }
      ],
      "label": [
        "0.875rem",
        {
          "lineHeight": "1.4286",
          "fontWeight": "700",
          "letterSpacing": "0.14em"
        }
      ]
    },
    "spacing": {
      "0": "0px",
      "px": "1px",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem",
      "24": "6rem",
      "32": "8rem"
    },
    "borderRadius": {
      "none": "0px",
      "sm": "3px",
      "DEFAULT": "4px",
      "md": "4px",
      "full": "9999px"
    },
    "borderWidth": {
      "DEFAULT": "2px",
      "0": "0px",
      "hairline": "1px",
      "base": "2px",
      "heavy": "3px",
      "strong": "4px",
      "accent": "6px"
    },
    "screens": {
      "sm": "640px",
      "md": "960px",
      "lg": "1280px",
      "xl": "1920px"
    },
    "boxShadow": {
      "none": "none"
    },
    "maxWidth": {
      "content": "1728px",
      "measure": "68ch",
      "none": "none",
      "full": "100%"
    },
    "backgroundImage": {
      "signature-on-dark": "var(--gm-gradient-on-dark)",
      "signature-on-light": "var(--gm-gradient-on-light)"
    },
    "transitionDuration": {
      "DEFAULT": "200ms",
      "fast": "120ms",
      "base": "200ms"
    },
    "transitionTimingFunction": {
      "DEFAULT": "cubic-bezier(0.2, 0, 0, 1)"
    },
    "zIndex": {
      "base": "0",
      "sticky": "100",
      "overlay": "200",
      "modal": "300",
      "toast": "400"
    }
  },
  corePlugins: { container: false },
};
